[package]
name = "sensor-display"
version = "0.1.0"
edition = "2021"

[dependencies]
sensor-core = { git = "https://github.com/RouHim/sensor-core.git" }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
message-io = { version = "0.17", default-features = false, features = ["tcp"] }
image = "0.24"
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_8"] }

# arm-unknown-linux-gnueabi, arm-musleabi
# alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:arm-musleabi'
# rust-musl-builder cargo build --release

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
strip = true # Strip debug symbols