[package]
name = "sensor-display"
version = "0.1.0"
edition = "2021"

[dependencies]
sensor-core = { git = "https://github.com/RouHim/sensor-core.git" }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
message-io = { version = "0.17", default-features = false, features = ["tcp"] }
image = "0.24"
eframe = "0.22"
egui_extras = { version = "0.22", features = ["image"]  }

# cross build --target=arm-unknown-linux-gnueabihf --release

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
strip = true # Strip debug symbols